name: "Verify run-buildifier action"
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * *"

jobs:
  verify-setup-buildifier:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows]
        buildifier: [5.1.0, 5.0.0]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: ${{ matrix.os == 'windows' }}

      - name: Setup repository
        uses: actions/checkout@v3

      - name: Run buildifier ${{ matrix.buildifier }} on formatted files
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/success

      - name: Run buildifier ${{ matrix.buildifier }} on ill formatted files
        id: failed-buildifier-check
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/fail
        continue-on-error: true

      - name: Verify failure
        run: exit 0
        if: steps.failed-buildifier-check.outcome == 'failure'

      - name: Verify failure
        run: exit 1
        if: steps.failed-buildifier-check.outcome == 'success'

  verify-setup-buildifier-diff:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: ${{ matrix.os == 'windows' }}

      - name: Setup repository
        uses: actions/checkout@v3

      - name: Run buildifier ${{ matrix.buildifier }} on formatted files
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/success
          mode: diff

      - name: Run buildifier ${{ matrix.buildifier }} on ill formatted files
        id: failed-buildifier-check
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/fail
          mode: diff
        continue-on-error: true

      - name: Verify failure
        run: exit 0
        if: steps.failed-buildifier-check.outcome == 'failure'

      - name: Verify failure
        run: exit 1
        if: steps.failed-buildifier-check.outcome == 'success'
