name: "Verify run-buildifier action"
concurrency:
  group: ${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * *"

jobs:
  verify-setup-buildifier:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        buildifier: [5.1.0]
    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Run run-buildifier action on dir1 ${{ matrix.buildifier }}
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/dir1

      - name: Run run-buildifier action on dir2 ${{ matrix.buildifier }}
        uses: ./
        with:
          buildifier-version: ${{ matrix.buildifier }}
          path: tests/dir2
